### PR TITLE
Add support for nodei.co badge

### PR DESCRIPTION
**Pull request by digitalsadhu**
https://nodei.co/

### CODE REVIEW

**Comment by balupton** [comment]
Can't decide on `nodeicoParams` or `nodeicoOptions`, as `nodeicoParams` is fitting as they are query-string parameters, but really, they are optional query-string parameters, so `nodeicoOptions` is probably fitting.

Other option is `nodeicoQueryParams` or `nodeicoQueryOptions` in case in the future there is some other config that is needed, where we have `nodeicoSomething` and `nodeicoOptions` could be confusing as to why `Something` isn't inside `nodeicoOptions` instead of alongside it.

Perhaps `nodeicoQueryString` which can be string or object. That would actually work very well. Let's do that.

**Comment by digitalsadhu** [comment]
Applied some fixes, how we looking?

**Comment by balupton** [comment]
Merging now.

**Comment by balupton** [comment]
It should be noted that the string mode is not tested. I'll add a note for this in the merge. Also tempted to call it `nodeicoQueryString` and just have object support, as that seems easier.

**Comment by balupton** [comment]
Released to v1.2.1! 👍

**Pull request merged**
